apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ordersvc.fullname" . }}
  labels:
    {{- include "ordersvc.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  APP_ENVIRONMENT: {{ .Values.config.appEnvironment | quote }}
  APP_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  HTTP_PORT: {{ .Values.config.httpPort | quote }}
  GRPC_PORT: {{ .Values.config.grpcPort | quote }}
  DATABASE_HOST: {{ .Values.config.databaseHost | quote }}
  DATABASE_PORT: {{ .Values.config.databasePort | quote }}
  DATABASE_USER: {{ .Values.config.databaseUser | quote }}
  DATABASE_NAME: {{ .Values.config.databaseName | quote }}
  DATABASE_SSL_MODE: {{ .Values.config.databaseSSLMode | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  REDIS_DB: {{ .Values.config.redisDB | quote }}
  KAFKA_BROKERS: {{ .Values.config.kafkaBrokers | quote }}
  KAFKA_TOPIC: {{ .Values.config.kafkaTopic | quote }}
  KAFKA_GROUP_ID: {{ .Values.config.kafkaGroupID | quote }}
