{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ordersvc.fullname" . }}
  labels:
    {{- include "ordersvc.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "ordersvc.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
{{- end }}
