apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ordersvc.fullname" . }}
  labels:
    {{- include "ordersvc.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
